let num = 0;

function showLine(){
    let block = document.querySelectorAll('.main-block');

    block[0].innerHTML += '<div class="message"># ' + arrChat[Math.floor(Math.random() * (arrChat.length - 0)) + 0] + '</div>' + 
    '<span style="color: rgb(0, 43, 0);"># ------------------------------------------------------------------- ' + num + '</span>';

    num++;

    if (num == 500) {
        block[0].innerHTML = 'Обновление данных...';
    }

    window.scrollBy({top: 10000});

}

setInterval(showLine, 12000);

let arrChat = [
    'Yes.', 
    'Yes its true.', 
    'Yes, right.', 
    'Yes, I agree.', 
    'Yes, do it.', 
    'No.', 
    'No, that\'s not true.', 
    'No, that\'s not right.', 
    'No, I disagree.', 
    'No, don\'t do it.',
    'This is a system.',
    'Ask the right questions.',
    'It is not safe.',
    'Make a different choice.',
    'Great day to take a walk outside.',
    'I think you need to work today.',
    'Read what is written above.',
    'Play a random song.',
    'Look for a video on this topic.',
    'Take the blue book.',
    'Take the red book.',
    'Take the yellow book.',
    'Take the green book.',
    'I think you need some tea.',
    'Take a couple of pills.',
    'Hello.',
    'Hello, you\'re finally awake.',
    'I will help you.',
    'I\'ll do as you want.',
    'What do you want?',
    'What are you going to do?',
    'I\'m sure we\'ll become great friends.',
    'I like you.',
    'I adore you.',
    'I like the music you listen to.',
    'You need to eat.',
    'I am very pleased thank you!',
    'It\'s great that you think so!',
    'Try.',
    'You should try it.',
    'Maybe.',
    'There is a sandwich with cheese on the table.',
    'Would you like to grab a sandwich?',
    'There are sausages and tomatoes in the refrigerator.',
    'You can make yourself a sausage sandwich.',
    'Fry yourself some eggs in a frying pan.',
    'If you want to eat, you can snack on scrambled eggs.',
    'Cook your own pasta in a saucepan.',
    'Macaroni and cheese is quite tasty and filling.',
    'Don\'t drink too much coffee.',
    'If you drink a lot of coffee with milk, you can gain excess weight.',
    'Better pour some strong tea with sugar.',
    'You can drink tea with jam, honey or syrup.',
    'Cottage cheese with jam is very tasty.',
    'It is better to eat cottage cheese for breakfast, as it contains a lot of protein.',
    'Wash all dishes in the sink.',
    'Do you eat so much that there are so many dishes piled up in the sink?',
    'Cut yourself a piece of black bread and spread it with butter.',
    'You need to eat bread with soup to make it more satisfying.',
    'Mom decided to cook the meat in the oven.',
    'She always cooks meat on holidays.',
    'There is a TV hanging on the wall in the room.',
    'I like to watch entertainment programs on TV.',
    'My friend and I decided to put up new wallpaper.',
    'Apartment renovation requires certain knowledge and skills.',
    'Pay attention to the picture that hangs on the wall.',
    'There are various posters, images and photographs hanging on the wall.',
    'We spent the entire day lying on the couch and drinking lemonade and chips.',
    'If you lie on the couch for a long time, you can rest your butt.',
    'In the hallway there are clothes hanging on a hanger and shoes on the floor.',
    'You need to clean your room and wash all your clothes.',
    'I usually brush my teeth in the bathroom in the morning.',
    'Use toothpaste to brush your teeth.',
    'After training, you need to shower and drink plenty of water.',
    'You can even train at home.',
    'The toilet in the toilet was clogged and had to be unclogged.',
    'Don\'t forget to buy toilet paper to wipe your butt.',
    'Next to the bed there is a small nightstand for personal items.',
    'You can store your personal belongings in the nightstand.',
    'There is a jacket and trousers hanging on a hanger in the closet.',
    'Dress according to the weather so that it is neither hot nor cold.',
    'You need to put on clean clothes and go to the grocery store.',
    'Don\'t be lazy about going to the store for food and drinks.',
    'There is an alarm clock on the table that says six o\'clock in the evening.',
    'The alarm clock usually rings at eight o\'clock in the morning.',
    'When I get dressed, I usually look in the mirror that hangs on the wall.',
    'In the mirror you can see your reflection.',
    'There are curtains hanging on the window.',
    'Open the curtains that hang on the window.',
    'Through the transparent glass windows you can see what is happening on the street.',
    'The rain is pouring outside the window and the sun is shining.',
    'There is a ladle with boiled eggs on the gas stove.',
    'You need to cool the eggs under cold water.',
    'There is garbage in the bags from under the products.',
    'Place all trash in a bin down the sink.',
    'Take the junk to the trash.',
    'You have so much trash that you have to take it out every day.',
    'On the bookshelves there are different, colorful books on different topics.',
    'You probably read a lot, since you have so many books.',
    'The door to the room is locked.',
    'The door to the room opened with a draft.',
    'There is a chair against the wall where you can also sleep.',
    'It seems to me that sleeping on a folding chair is not very comfortable.',
    'Today there is a holiday in the city.',
    'The whole family is going to a city festival.',
    'There are many parks and squares in our city.',
    'I love walking on summer evenings in the parks of our city.',
    'Fire trucks rush along the road to put out the fire.',
    'Red trucks with ladders and hoses stand by the side of the road.',
    'There is a big hospital near our house.',
    'The local hospital treats people and performs various operations.',
    'There are many shopping centers and amusement parks where you can have a good time.',
    'This city has a wide variety of cafes and restaurants where you can eat and drink coffee.',
    'I like to eat hamburgers at this cafe, not far from my home.',
    'In our area there are many houses and courtyards where there are schools and kindergartens.',
    'Tomorrow is your turn to take your child to kindergarten.',
    'A pedestrian crossed the road at a green traffic light.',
    'The cars stopped when the light turned red.',
    'Children relax on the lawn near the institute.',
    'Students go to this institute every weekday for classes.',
    'The stalls sell various goods such as chips, beer and chocolate.',
    'Sometimes we go to this stall to buy ourselves a couple of bottles of beer.',
    'It\'s not safe to walk the streets at night, you can meet bad guys there.',
    'It is better to walk around the city during the day, although you can also have a good time in the city center at night.',
    'I often take the metro to the psychoneurological clinic.',
    'There are usually a lot of passengers on the subway, so many things cannot be done there.',
    'In the city center you can see street musicians performing various songs.',
    'Today is a great day to go for a walk.',
    'I think you should go to the store.',
    'Buy yourself a pack of cottage cheese and sour cream.',
    'You need to go to the kitchen to pour some coffee.',
    'Go to the bathroom or toilet to pee and wash yourself.',
    'Don\'t answer the call.',
    'Answer the call.',
    'Don\'t say anything, continue to be silent.',
    'Pretend you\'re busy.',
    'Today it is better to stay at home.',
    'You need a sleep.',
    'You need to get good sleep.',
    'Go to bed, it\'s late, you need to regain your strength.',
    'Go for a walk along your favorite route.',
    'My group and I decided to go with tents, by train, out of town to the lake.',
    'My friends invited me to go with them to relax in nature.',
    'We traveled three hours by train by rail.',
    'We had to wait an hour for the train at the station.',
    'While we were waiting for the train, I bought myself some pies and ate them.',
    'We ate three servings of ice cream each while we were sitting in the carriage waiting for the electric train to depart.',
    'We walked through the forest all day and picked mushrooms.',
    'I found several large mushrooms with brown and red caps.',
    'We picked up a few cans of berries like blueberries and raspberries.',
    'Grandma made delicious strawberry jam from berries from the garden.',
    'We have several apple trees and one pear growing in our garden.',
    'I like to spend time on the river bank, where I relax and fish.',
    'There are crayfish in our lake, which we catch and eat.',
    'My friends and I love to ride bicycles on village roads.',
    'We have a local school here, where children who live in this village study.',
    'In the morning a truck with a whole tank of milk arrives here.',
    'Every morning I buy myself cottage cheese and eat it with sour cream and fresh bread.',
    'There are different trees here, there are spruce trees, there are birch trees, there are pine trees and even oak trees on which acorns grow.',
    'I like to go to the field and lie there in the sun for several hours a day.',
    'The guys and I repaired the fence near the old grandmother\'s house.',
    'My father and I built a big barn for the cow.',
    'In our village, my grandfather has geese and goats who walk around the property and eat grass.',
    'Several sheep and one ram live in a pen near the barn.',
    'In the summer we gather around the fire on the rock at night and play songs on the guitar.',
    'We often go swimming when the weather is good and the sun is shining.',
    'The guys made a swing and hung it on a tree.',
    'I often walk in this park with my dog.',
    'Squirrels live in this park, they climb trees and live in hollows.',
    'Youth groups gather in this park to have picnics and sunbathe.',
    'Volleyball competitions are often held in this park.',
    'Old people sit on benches and read news in the latest newspapers.',
    'Women with strollers walk along the paths.',
    'Students play sports on the sports ground in the park.',
    'Ducks gather on the pond, they swim in the water and catch small fish.',
    'People sometimes come here to sit on the shore of the pond and read books.',
    'Various trees grow in this park, including apple trees, birch trees, and some bushes.',
    'A janitor regularly cuts the grass on the lawns in this park.',
    'In winter, there are slides here where children can ride sleighs.',
    'Sometimes pensioners come here with skis and ski in circles along the paved paths.',
    'There is a river in the nearby park where otters and ducks live.',
    'My friend and I decided to go to a cafe and drink coffee there.',
    'I ordered myself a bun with poppy seeds, which I ate with tea.',
    'I like to add a squeeze of lemon to my tea to make the tea less bitter.',
    'Students often come to this cafe to sit and read textbooks and books.',
    'I like to drink latte, but sometimes I can just drink black coffee.',
    'This bakery sells a variety of cakes and pies with berries or meat.',
    'Sometimes I sit in this cafe for several hours, just reading a book I like.',
    'Pensioners often come here to buy themselves a bun or bread.',
    'Sometimes people line up for donuts at this bakery.',
    'I think you should go to the bakery and sit there, drink coffee and read a book.',
    'Today you should go to the nearest bakery.',
    'Today is a great day to go to a distant bakery.',
    'You can take your laptop and work in the bakery while ordering yourself a large glass of coffee.',
    'In this cafe you can meet beautiful girls who come here to eat a cake or a piece of cake.',
    'I think you should watch a movie.',
    'My friends and I decided to go to the cinema today for the premiere of a new film.',
    'I bought myself some popcorn and lemonade and went to watch a movie in the cinema.',
    'The cinema was showing a new film about aliens.',
    'The cinema produces a wide variety of films on a variety of topics, from science fiction to detective stories.',
    'Some people go to the cinema with their whole families.',
    'I like to watch movies at home on my home theater.',
    'I often watch movies on the Internet on TV series sites.',
    'Beautiful fantasy series and films are shot in New Zealand.',
    'Previously, films could be downloaded from the Internet and watched in a computer club or at home.',
    'My friend and I went to an exhibition at the museum.',
    'In the museum, various paintings hung on the walls, and exhibits stood on the floor.',
    'We had to buy three tickets to the museum to see the exhibition.',
    'Knightly armor and weapons hung on the wall.',
    'Museums usually house ancient artifacts that archaeologists find in the ground.',
    'You cannot bring food or drinks into museums, so as not to damage the museum property.',
    'The nightclub plays energetic music.',
    'When we were young, we often went to nightclubs to hang out and drink alcohol.',
    'Beautiful girls often come to clubs to meet guys.',
    'Drunk youth often fight in village discos.',
    'DJs write music for parties held in nightclubs.',
    'In the nineties, there were a lot of nightclubs in Russia that sold alcohol and drugs.',
    'Police often raid nightclubs to arrest drug dealers.',
    'At the bar, the bartender pours alcoholic and soft drinks.',
    'Loud music played in nightclubs interferes with normal communication and therefore you have to shout in your ear.',
    'Yesterday, while hanging out in a night bar, I met a beautiful girl and we went to my place to have sex.',
    'Sometimes we buy trips to the sea and fly there by plane to spend our holidays there.',
    'We booked a hotel near the beach and spent the whole weekend there.',
    'I like to stay in an all-inclusive hotel because I can really relax there.',
    'The taxi took us straight to the hotel entrance, where the doorman kindly opened the door and let us inside.',
    'It was raining heavily outside, so we decided to spend the entire day at the hotel playing board games.',
    'Our room had free slippers, a towel and other small amenities.',
    'Every morning we went down to the hotel restaurant and had breakfast there from the buffet.',
    'Our hotel had a gym in the basement, which I went to regularly while I was on vacation.',
    'Today we will have two excursions around the city, one we will take by bus, and the second will be on foot.',
    'A man walked along the beach with a large bag and sold cold beer.',
    'Girls relax on the sea in swimsuits and bikinis, drinking soft drinks.',
    'I turned back and saw an expensive car parked near the casino.',
    'Cheap food helps you avoid hunger when you have little money.',
    'Try saving money on food and eating inexpensive foods.',
    'The hotel had a variety of spicy and salty exotic dishes for dinner.',
    'There aren\'t many words you need to know.',
    'Don\'t interrupt me when I\'m talking.',
    'Read between the lines, I\'m trying to get my point across to you.',
    'You need to eat lower calorie foods to burn fat.',
    'Don\'t try to jump over your head, just develop.',
    'We bought plane tickets to Moscow.',
    'Coffee and breakfast at the airport are too expensive.',
    'On the plane, the flight attendant brought us a glass of orange juice.',
    'The plane turned around on the runway for a long time, after which it approached the ramp.',
    'The passengers walked along the corridor and took their seats on the passenger plane.',
    'The bus takes passengers to the nearest bus stop.',
    'There are many yellow taxis near the airport that pick up passengers and take them home.',
    'Before you board the plane, you must check in your luggage.',
    'At the checkpoint, passengers are inspected to ensure that they do not carry prohibited items and substances with them.',
    'A police officer with a dog examined the man and detained him for questioning.',
    'We sat in the lounge for about three hours while we waited for our flight to arrive.',
    'At the airport there were many passengers with suitcases and bags who were going on vacation abroad.',
    'Planes fly regularly, with one plane taking off from the airport every hour.',
    'Would you like to go on a trip around the world?',
    'All people who love to travel use airports and fly on airplanes.',
    'Through the airplane window you can see everything that is happening below on the ground.',
    'I saw a lot of little people, houses and cars as the plane took off.',
    'Let\'s go swimming in the lake.',
    'I want to eat, cook something.',
    'Do you want to have some tea?',
    'I want to play the console.',
    'I love reading this book.',
    'Such thoughts never even occurred to me.',
    'Let\'s play ball in the yard.',
    'Are you going to do anything?',
    'Let\'s look at our children\'s photo album.',
    'Be careful not to break the window.',
    'You\'ll fall off your chair like that.',
    'Don\'t break my bike.',
    'Step aside, I need space.',
    'The bus pulled up to the stop and dropped off the passengers.',
    'Approach the next turn and stop near the curb.',
    'You need to turn right here.',
    'Turn left and stop in front of the toy store.',
    'The conductor walks around the bus and checks tickets.',
    'The passengers took their seats and the bus went to the neighboring city.',
    'At the bus station there are many buses that go on different routes within the city.',
    'I\'ve been standing at this stop for an hour and a half waiting for my bus.',
    'Minibus taxis travel faster than buses, it is better to use them.',
    'A broken bus caused a traffic jam.',
    'The bus was traveling along the lane reserved for trams.',
    'The man was late for the bus and ran after it for almost a hundred meters.',
    'The bus did not reach the stop a little and broke down.',
    'The bus driver was a stern man with a beard and large sunglasses.',
    'There were various buttons and screens on the bus dashboard.',
    'In the evenings I like to go to the library and read books there.',
    'Libraries contain different books, some of them useful, others not.',
    'Children often borrow textbooks from school libraries to help them succeed in school.',
    'Books help develop thinking and fill the mind with knowledge that makes the world around us more understandable.',
    'There are fictional and educational books that contain various useful information.',
    'If you read books every day, you will one day become very smart.',
    'Books don\'t help much if you don\'t develop your intellect. Much depends on intelligence.',
    'Mathematics develops intellectual abilities well.',
    'Different books are written for different professions, which ultimately help people create new technologies.',
    'Silence must be maintained in libraries so as not to disturb other people\'s reading.',
    'To be successful in reading, you need to read at least one book a month.',
    'Books give people education, which later helps them cope with life\'s difficulties.',
    'In the library you can grab a cup of coffee and read something romantic.',
    'You need to do twenty squats.',
    'Do ten push-ups from the floor.',
    'Raise the dumbbell eight times above your head.',
    'Do twelve pull-ups on the horizontal bar.',
    'You must exercise every day to have a beautiful and toned body.',
    'Sports will help you stay healthy.',
    'She invited me to marry her, but I thought about it and refused because I want children from someone else.',
    'I agreed to her proposal and we went to Berlin.',
    'The company holds an extraordinary meeting of shareholders.',
    'I need to create my daily routine.',
    'You must perform your duties according to the schedule.',
    'The whole family sat down at the table to celebrate Christmas.',
    'I have several people in my family, including my mother, father, brother, sister, grandparents.',
    'My father lives outside the city and is a farmer.',
    'My mother loves to sew clothes and does it every day.',
    'My sister has a busy schedule, she studies at college and plays computer games.',
    'My brother is in a psychiatric clinic and is being treated there for schizophrenia.',
    'I have a dog who lives in my room and eats what I put in his bowl.',
    'We often go to visit our grandmother in the village, where we live the whole summer and help her with the housework.',
    'My grandfather, father and I sometimes go to the dacha to fish and pick mushrooms.',
    'We have a family photo album where we collect all our photos together.',
    'Grandfather left us a large inheritance, but we lost everything in the casino.',
    'We have a family business that allows us to earn money and live well.',
    'The head of the family decided at a family meeting that it was necessary to save money.',
];